apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools   # тут уже має бути встановлений ArgoCD
spec:
  project: default
  source:
    repoURL: "https://github.com/EugeneChurylov/mlops-mlflow-helm.git"  # ЗАМІНИ на свій репозиторій після пушу
    targetRevision: main
    path: mlflow-helm/charts/mlflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
